#/control/execute mac/visu.mac
#/vis/disable
/control/execute mac/verbose.mac

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# World
/gate/world/setMaterial            Vacuum
/gate/world/geometry/setXLength    0.5 m
/gate/world/geometry/setYLength    0.5 m
/gate/world/geometry/setZLength    0.5 m





# Insert phantom
/gate/world/daughters/name                              crackFOV
/gate/world/daughters/insert                            ImageNestedParametrisedVolume
/gate/crackFOV/geometry/setHUToMaterialFile           data/crack-HU2mat.txt
/gate/crackFOV/geometry/setImage                      data/crack_45degree_4.mhd
/gate/crackFOV/geometry/TranslateTheImageAtThisIsoCenter 0 0 0 mm
/gate/crackFOV/vis/forceWireframe

# The patient is rotated instead of the linac => change rotation sign
/gate/crackFOV/moves/insert rotation
/gate/crackFOV/rotation/setSpeed 45 deg/s
/gate/crackFOV/rotation/setAxis 0 0 1


/gate/crackFOV/moves/insert orbiting
/gate/crackFOV/orbiting/setSpeed  360.0  deg/s
/gate/crackFOV/orbiting/setPoint1 0 0 0 cm
/gate/crackFOV/orbiting/setPoint2 1 1 0 cm

#=====================================================
# PHYSICS
#=====================================================
/gate/physics/addPhysicsList                          emstandard_opt3
/gate/physics/Gamma/SetCutInRegion                    world 10 mm
/gate/physics/Gamma/SetCutInRegion                    crackFOV 0.1 mm

# Detection plane
/gate/world/daughters/name                   DetectorPlane
/gate/world/daughters/insert                 box
/gate/DetectorPlane/geometry/setXLength      1.560 mm
/gate/DetectorPlane/geometry/setZLength      1 nm
/gate/DetectorPlane/geometry/setYLength      0.780 mm
/gate/DetectorPlane/placement/setTranslation 0 0 -150 mm
/gate/DetectorPlane/setMaterial              Vacuum
/gate/DetectorPlane/vis/setVisible           1
/gate/DetectorPlane/vis/setColor             yellow

# Fluence of gamma
/gate/actor/addActor FixedForcedDetectionActor ffda
/gate/actor/ffda/attachTo                     world
/gate/actor/ffda/setDetector                  DetectorPlane
/gate/actor/ffda/setDetectorResolution        1200 600
/gate/actor/ffda/binningFactor                10 10
/gate/actor/ffda/primaryFilename              output/primary/primary_1200.mha    
/gate/actor/ffda/fresnelFilename              output/fresnel/fresnel_1200.mha
/gate/actor/ffda/geometryFilename             output/geo/geo_1200.xml
/gate/actor/ffda/energyResolvedBinSize        0 keV

#=====================================================
# INITIALISATION
#=====================================================
/gate/run/initialize



# BEAM
#=====================================================

/gate/source/addSource mybeam          gps
/gate/source/mybeam/gps/particle       gamma
#/gate/source/mybeam/gps/ene/type       Mono
#/gate/source/mybeam/gps/ene/mono      29 keV
/gate/source/mybeam/gps/energy         29. keV
/gate/source/mybeam/gps/polarization   1 0 0
/gate/source/mybeam/gps/pos/type       Plane
/gate/source/mybeam/gps/pos/shape      Rectangle
/gate/source/mybeam/gps/pos/halfx      3 mm
/gate/source/mybeam/gps/pos/halfy      2 mm
/gate/source/mybeam/gps/pos/centre     0 0 150 mm
/gate/source/mybeam/gps/ang/type       focused
/gate/source/mybeam/gps/ang/focuspoint 0 0 10 km



/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

/gate/application/setTimeSlice 1 s
/gate/application/setTimeStart 1 s
/gate/application/setTimeStop  2 s

/gate/application/setTotalNumberOfPrimaries 1000000
#/gate/application/setTotalNumberOfPrimaries 100
/gate/application/start

